name: CI - Build & Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  packages: write

jobs:
  build-and-test:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Verify System Java
        run: |
          java -version
          javac -version

      - name: Run Maven tests (H2)
        run: mvn -B -Dspring.profiles.active=test -Dgatling.skip=true test

      - name: Build Spring Boot jar (PROD)
        run: mvn -B -DskipTests -Dspring.profiles.active=prod -Dgatling.skip=true package

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: |
          IMAGE_NAME=ghcr.io/hrishabh6/karate-scala_learning/springboot-crud
          TAG=${{ github.sha }}
          docker build -t $IMAGE_NAME:$TAG .
          docker tag $IMAGE_NAME:$TAG $IMAGE_NAME:latest

      - name: Push Docker image to GHCR
        run: |
          IMAGE_NAME=ghcr.io/hrishabh6/karate-scala_learning/springboot-crud
          docker push $IMAGE_NAME:${{ github.sha }}
          docker push $IMAGE_NAME:latest
